// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TogoleseSolidarity.Infrastructure.Database;

#nullable disable

namespace TogoleseSolidarity.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250309201719_fewChanges")]
    partial class fewChanges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TogoleseAssociationSystem.Domain.Models.Claim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ClaimDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ClaimType")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NextOfKinContact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NextOfKinName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.ToTable("Claims");
                });

            modelBuilder.Entity("TogoleseAssociationSystem.Domain.Models.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEligibleToClaim")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("MembershipDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NextOfKin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NextOfKinContact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Postcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Relationship")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalClaimRemain")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cdedad9a-30b1-461a-87b2-8dbb30db6175"),
                            Address = "34 Bentley road",
                            City = "Birmingham",
                            DateOfBirth = new DateTime(2000, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "John",
                            IsActive = true,
                            IsEligibleToClaim = true,
                            LastName = "Doe",
                            MembershipDate = new DateTime(2025, 3, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            NextOfKin = "Brenda",
                            NextOfKinContact = "07459999999",
                            Postcode = "BR3 1AS",
                            Relationship = "sister",
                            Telephone = "07458893212",
                            Title = "Mr",
                            TotalClaimRemain = 2
                        },
                        new
                        {
                            Id = new Guid("fe7e9f0b-bfc9-4891-b123-65adde34880f"),
                            Address = "34 Bentley road",
                            City = "Birmingham",
                            DateOfBirth = new DateTime(1980, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Brenda",
                            IsActive = true,
                            IsEligibleToClaim = true,
                            LastName = "Love",
                            MembershipDate = new DateTime(2025, 3, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            NextOfKin = "John",
                            NextOfKinContact = "07459999999",
                            Postcode = "BR3 1AS",
                            Relationship = "brother",
                            Telephone = "07126678342",
                            Title = "Miss",
                            TotalClaimRemain = 2
                        },
                        new
                        {
                            Id = new Guid("6e4ba595-10df-4bf7-9b01-6a2c3412c960"),
                            Address = "5 Batman garden",
                            City = "Nottingham",
                            DateOfBirth = new DateTime(1970, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Smith",
                            IsActive = true,
                            IsEligibleToClaim = true,
                            LastName = "Joe",
                            MembershipDate = new DateTime(2025, 3, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            NextOfKin = "Jenny",
                            NextOfKinContact = "07459999999",
                            Postcode = "NG5 9AQ",
                            Relationship = "wife",
                            Telephone = "07894432123",
                            Title = "Mr",
                            TotalClaimRemain = 2
                        });
                });

            modelBuilder.Entity("TogoleseAssociationSystem.Domain.Models.MembershipContribution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ContributionName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfContribution")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.ToTable("MembershipContributions");
                });

            modelBuilder.Entity("TogoleseAssociationSystem.Domain.Models.Claim", b =>
                {
                    b.HasOne("TogoleseAssociationSystem.Domain.Models.Member", null)
                        .WithMany("Claims")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TogoleseAssociationSystem.Domain.Models.MembershipContribution", b =>
                {
                    b.HasOne("TogoleseAssociationSystem.Domain.Models.Member", null)
                        .WithMany("Memberships")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TogoleseAssociationSystem.Domain.Models.Member", b =>
                {
                    b.Navigation("Claims");

                    b.Navigation("Memberships");
                });
#pragma warning restore 612, 618
        }
    }
}
